### PR TITLE
93 make elements lay out properly and nest subcomponents

### PR DESCRIPTION
**Pull request by jfitzgerald1126**
- Fixed bugs in implementation to create properties and add properties to components from the web-interface
- Nest subcomponents inside of "parent" components instead of using a different edge type
- Structure the automatic layout (minor improvements needed)
- Added GitHub OAuth authentication with the use of an express.js proxy server

### CODE REVIEW

**Comment by ahincks** [comment]
When I run `npm` I get an error saying that `web-interface/src/node_modules` and `web-interface/node_modules/mdi-react` don't exist. Did you miss adding something to the commit or do I need to run something to get React to install something?

**Comment by jfitzgerald1126** [comment]
> When I run `npm` I get an error saying that `web-interface/src/node_modules` and `web-interface/node_modules/mdi-react` don't exist. Did you miss adding something to the commit or do I need to run something to get React to install something?

I think I forgot to add and commit the package.json for the new packages I used. Will fix after my lectures today.

**Comment by jfitzgerald1126** [comment]
New dependencies should be added.
It should work now with running `npm install` in both web-interface and server, before running npm start in both directories.

**Review by ahincks — CHANGES_REQUESTED** [review]
- Let's change the directory name from `server` to something a bit more descriptive.
- The sub/supercomponent visualisation is not working properly in all instances for me. But I can show you tomorrow when we meet.

**Review by ahincks — APPROVED** [review]

**Pull request merged**
