### PR TITLE
Summer2022

### PR DESCRIPTION
**Pull request by Dhananjhay**

### CODE REVIEW

**Comment by ahincks** [comment]
I merged in the changes I recently merged into the main branch. It seems to run well for me, but can you double check that everything runs well on your end? Then I can merge into main.

**Comment by ahincks** [comment]
It's been a while since this was opened: looks like it was ready to merge a couple of weeks ago. Do you think it can be merged at this point or do you still need to make any updates?

**Comment by Dhananjhay** [comment]
I am still working on some tasks, for example, the flag list page and I have to update the code to point towards the single source of error, but the website is functioning fine in a sense that there are no bugs.
 I have been busy with the update feature(replacing vertices and edges) of the JanusGraph but I can complete these side tasks by tonight and have the updated website ready to be used by tonight.

**Review by ahincks — APPROVED** [review]

**Comment by ahincks** [comment]
Thanks for getting it into shape! Go ahead and merge.

**Pull request merged**
